# Generated by Django 5.0.3 on 2024-04-05 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='user_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
